name: cd

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

env:
  RELEASE_PREFIX: "chore(main): release"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
